# Generated by Django 4.0 on 2021-12-16 01:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='teammember',
            name='phonenumber',
            field=phone_field.models.PhoneField(blank=True, help_text='phone number', max_length=31),
        ),
    ]
