# Generated by Django 4.0 on 2021-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_teammember_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[(0, 'Small'), (1, 'Medium')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
