# Generated by Django 4.0 on 2021-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
