# Generated by Django 4.0 on 2021-12-16 21:24

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phonenumber',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
