# Generated by Django 4.0 on 2021-12-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_teammember_rolename'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='rolename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
