# Generated by Django 4.0 on 2021-12-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_teammember_rolename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='rolename',
        ),
    ]
