# Generated by Django 4.0 on 2021-12-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_remove_teammember_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phonenumber',
            field=models.CharField(max_length=12),
        ),
    ]
